web: daphne --bind 0.0.0.0 --port $PORT {{cookiecutter.project_slug}}.asgi:application
worker: python manage.py rqworker default
scheduler: python manage.py rqscheduler default
dev_worker: honcho start -f Procfile_dev_worker
release: python manage.py migrate --noinput
