web: newrelic-admin run-program daphne --bind 0.0.0.0 --port $PORT {{cookiecutter.project_slug}}.asgi:application
worker: newrelic-admin run-python manage.py rqworker default short
scheduler: newrelic-admin run-python manage.py rqscheduler default short
dev_worker: honcho start -f Procfile_dev_worker
